### ISSUE TITLE
Yarn install fails

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#52]
```
error /Users/upstairs/dev/Padma-Frontend/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/upstairs/dev/Padma-Frontend/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.1.1/electron-v9.1.1-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/upstairs/dev/Padma-Frontend/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:390:28)
    at module.exports (/Users/upstairs/dev/Padma-Frontend/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/upstairs/dev/Padma-Frontend/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/Users/upstairs/dev/Padma-Frontend/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
```

**Comment by blahmonkey** [comment]
@mikkokotila Trying to reproduce here, but not able to do so (MacOS system)

Can try 2 things
1. `rm -rf node_modules` in the repo folder, then run `yarn`

2. If still same error, check out the branch from the below PR and see if this branch also fails`yarn install` ?
https://github.com/Lotus-King-Research/Padma-Frontend/pull/34

**Comment by mikkokotila** [comment]
So it looks like version 11 or greater is required. Also maybe have to be Node v15. Some info from [this link](https://moinism.medium.com/running-electron-on-apple-silicon-m1-mac-8d463342a2b5).

**Comment by blahmonkey** [comment]
1. Ah M1 issue. So we run into a decision point here. Should we just upgrade the whole base (electron 11 etc). It will affect all, not just M1. It will take a little time to make this shift, not immediate

2. Since the base code is common to the web and electron frontends, if we split the repo, we will need to have some kind of CI based auto pushing of changes in the core codebase from one repo to another. I think thats better to do down the line when we expand on the functionality? Right now it feels we may be better off investing this effort into the improvements we wanted to make...for instance if a team takes over, then it can be one of their first tasks, to separate the repos

**Comment by mikkokotila** [comment]
My thesis so far about the matter is that the resolution is to have a newer version of Electron (above 11...9 is already EOL anyway), but I think other deps have to change with it as well. If just change Electron, then many more issues arise as a result.

> Since the base code is common to the web and electron frontends, if we split the repo, we will need to have some kind of CI based auto pushing of changes in the core codebase from one repo to another. I think thats better to do down the line when we expand on the functionality

Sure, I think the immediate case is just to be able to run the development environment as per the documentation or in an alternate way. And then before closing this current window, handling #51.

**Comment by mikkokotila** [comment]
Here is what makes it work with npm: 

```
 },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.4.0",
    "@vue/cli-plugin-eslint": "^4.4.0",
    "@vue/cli-plugin-pwa": "^4.4.0",
    "@vue/cli-plugin-router": "^4.4.0",
    "@vue/cli-plugin-vuex": "^4.4.0",
    "@vue/cli-service": "^4.4.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "^15.0.0",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^6.2.2",
    "sass": "^1.42.1",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-electron-builder": "^2.0.0-rc.4",
    "vue-template-compiler": "^2.6.11"
  }
}
```
For the sake of completeness, the commands: 

```
npm install
source .env-devapi
npm run serve
```

**Comment by blahmonkey** [comment]
I think we will approach in this order
1. @rabtenster will complete basic UI work (without the updated API)
2. I will work with that branch and migrate electron, node-sass, etc - the goal will be to verify the UI work as well as verifying that all steps work fine with the upgraded dependencies. Also electron is a complex dependency because it works at OS level (native code and integrated with the underlying OSes) so I will have to look at the changes in the releases between v9 and v15 - some of these can potentially break the app if we arent careful
3. @rabtenster will then integrate the updated API
4. I will then look at the docker/m1 issue. This seems more tricky and also lower priority since its only for production build which CI will do anyway

**Comment by mikkokotila** [comment]
@blahmonkey I think this is done, right? Feel free to close.

**Comment by blahmonkey** [comment]
It will autoclose with merging of linked PR, I will de-draft
